# This is a basic workflow to help you get started with Actions

name: create-dylib

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile-dylib:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
      - name: Compile tweak
        run: |
          cd /Users/runner/work/LuckySpeeder/LuckySpeeder
          chmod +x build.sh
          bash build.sh
          ls
      - name: Upload iPhone ARM64 file artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: LuckySpeedTweakiPhoneARM64
          path: /Users/runner/work/LuckySpeeder/LuckySpeeder/LuckySpeeder-iphone-arm64.dylib
      - name: Upload MacOS ARM64 file artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: LuckySpeedTweakMacOSARM64
          path: /Users/runner/work/LuckySpeeder/LuckySpeeder/LuckySpeeder-macos-arm64.dylib
      - name: Upload MacOS x86 file artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: LuckySpeedTweakMacOSx86
          path: /Users/runner/work/LuckySpeeder/LuckySpeeder/LuckySpeeder-macos-x86.dylib
  create-release:
    needs: 
      - compile-dylib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: download results from job compile-dylib iPhone ARM64 file
        uses: actions/download-artifact@v4
        with:
          name: LuckySpeedTweakiPhoneARM64
      - name: download results from job compile-dylib MacOS ARM64 file
        uses: actions/download-artifact@v4
        with:
          name: LuckySpeedTweakMacOSARM64
      - name: download results from job compile-dylib MacOS x86 file
        uses: actions/download-artifact@v4
        with:
          name: LuckySpeedTweakMacOSx86
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "LuckySpeeder with more multipliers to choose of!"
          body: "Date: 2024-12-12-04-25 This is a fork which adds more multipliers to the overlay. Injection this dylib into a iPA for Sideloading with your favorite tool or directly inject it into an app via \"TrollFools\""
          draft: 0
          prerelease: 0
          tag_name: v0.0.2-1
          files: |
            LuckySpeeder-iphone-arm64.dylib
            LuckySpeeder-macos-arm64.dylib
            LuckySpeeder-macos-x86.dylib
